name = "cf-worker-ws-dev123"
main = "src/index.js"
compatibility_date = "2024-01-01"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "b46540ea-7a59-4fc4-84bf-7ab6cc6e1623"
# TROJAN_PASSWORD = "your-trojan-password"  # Optional: If not set, UUID will be used as password
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
